# # Scraping Data From Movies

# # -*- coding: utf-8 -*-
# """Scrap IMDB.ipynb

# Automatically generated by Colaboratory.

# Original file is located at contributor (Ashwani and Abhishek)
#     https://colab.research.google.com/drive/13BBJeWAOc2mtlJH89p78nWvAWlgHPPI4
# """

# import requests
# from bs4 import BeautifulSoup

# page_link = "https://www.imdb.com/search/title/?genres=drama&groups=top_250&sort=user_rating,desc"
# page_response = requests.get(page_link, timeout=5)
# page_content = BeautifulSoup(page_response.content, "html.parser")

# """**Fecting Movies Name**"""

# l = page_content.find_all("h3")
# movies = []
# for i in range(50):
#   movies.append(l[i].find_all("a")[0].text)

# """**Fetching Movies Year**"""

# year = []
# for i in range(50):
#   year.append(l[i].find_all("span",{"class","lister-item-year"})[0].text[1:-1])
# year = [int(each) for each in year]

# """**Fetching Movies Ratings**"""

# lrating = page_content.find_all("div",{"class":"ratings-imdb-rating"})
# ratings = []
# for i in range(50):
#   ratings.append(lrating[i].text[2:-1])

# """**Fetching Movies Cast**"""

# castlist = page_content.find_all("div",{"class":"lister-item-content"})
# cast = []
# for i in range(50):
#   l = castlist[i].find_all("p",{"class":""})[0].text.split("\n")
#   l = [each.strip() for each in l]
#   member = []
#   for x in reversed(l):
#     if(x == "Stars:"):
#       break
#     member.append(x)
#   member = member[1:]
#   member = [each.strip(",") for each in member]
#   cast.append(member)
# # cast

# """**Fetching Movies Directors**"""

# castlist = page_content.find_all("div",{"class":"lister-item-content"})
# directors = []
# for i in range(50):
#   directors.append(castlist[i].find_all("p",{"class":""})[0].a.text)
# # directors

# """**Final List of Movies**"""

# moviesList = []
# for i in range(50):
#     moviesList.append({"id":i+1,"Name":movies[i],"Year":year[i],"Rating":ratings[i],"Director":directors[i],"Stars":cast[i]})


# Building Connection with database
import mysql.connector
from passwd import *

cnx = mysql.connector.connect(user='root', password=password,
                              host='localhost',
                              database='IMDB')

cursor = cnx.cursor();

# # Creating Movies Table
# sql_cmd = ( "CREATE TABLE IF NOT EXISTS movies ( movies_id INT PRIMARY KEY AUTO_INCREMENT," 
#           "name varchar(250) , rating varchar(32) NOT NULL,"
#           " year INT NOT NULL )" )
# cursor.execute(sql_cmd)

# for each in moviesList:
#      sql_cmd = 'INSERT INTO movies(name,rating,year) values ("{}","{}",{})'.format(each['Name'],each['Rating'],each['Year'])
#      cursor.execute(sql_cmd) 

# # Creating Stars Table
# sql_cmd = ( "CREATE TABLE IF NOT EXISTS stars ( movies_id INT NOT NULL, " 
#           "name varchar(250) NOT NULL )" )
# cursor.execute(sql_cmd)

# for movie in moviesList:
#      for star in movie["Stars"]:
#           sql_cmd = 'INSERT INTO stars(movies_id,name) values ("{}","{}")'.format(movie['id'],star)
#           cursor.execute(sql_cmd)


# # Creating Director Table
# sql_cmd = ( "CREATE TABLE IF NOT EXISTS directors ( movies_id INT NOT NULL, " 
#           "name varchar(250) NOT NULL )" )
# cursor.execute(sql_cmd)

# for movie in moviesList:
#      sql_cmd = 'INSERT INTO directors(movies_id,name) values ("{}","{}")'.format(movie['id'],movie['Director'])
#      cursor.execute(sql_cmd)

cnx.commit();
cnx.close();